name: 'NCC compile'
description: 'Use @zeit/ncc to compile js or ts files into one file'
inputs:
  entry-file:  # id of input
    description: 'Location of the entry file'
    required: true
    default: 'src/index.js'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.entry-file }}
